### PR TITLE
How to explain ip address with netmask.

### PR DESCRIPTION
**Pull request by orsenthil**
How to explain ip address with netmask using `ipcalc` utility.

### CODE REVIEW

**Comment by orsenthil** [comment]
It is from this tool http://jodies.de/ipcalc

**Comment by orsenthil** [comment]
Ping. Would the maintainers like to merge this?

**Comment by nonunicorn** [comment]
Hey man, sorry for being slow, we're on the way to process this soon. Thanks for your contribution.

**Comment by nonunicorn** [comment]
Thanks again man, we've split that into 2 pieces and deployed:
- https://onelinerhub.com/ubuntu/how-to-explain-ip-netmask
- https://onelinerhub.com/ubuntu/how-to-use-ipcalc-with-ip-address

**Comment by orsenthil** [comment]
Excellent. I will contribute more from my notes. :)

**Pull request merged**
