### PR TITLE
First Contributions (ffmpeg, git and PHP updates)

### PR DESCRIPTION
**Pull request by lucablackwell**
Found this repo about an hour ago, thought I'd contribute. Open to suggestions and changes of course.

### CODE REVIEW

**Comment by lucablackwell** [comment]
#1428

**Comment by lucablackwell** [comment]
the golang one is issue #1067 btw

**Comment by nonunicorn** [comment]
Thanks so much for the high quality code samples, man!

Deployed:
- https://onelinerhub.com/php/change_colour_of_text
- https://onelinerhub.com/golang/for_loop
- https://onelinerhub.com/git/make_a_branch_with_local_changes
- https://onelinerhub.com/ffmpeg/get_duration

**Comment by lucablackwell** [comment]
> Thanks so much for the high quality code samples, man!

You're more than welcome! Figured I might as well put the (pretty limited lol) knowledge that I have into here, will help me refresh on some stuff I figured out but haven't done for a while too. More commits are on their way :smile:

**Comment by nonunicorn** [comment]
Great news for us, thanks! Feel free also to add new technologies if you feel so.

**Pull request merged**
